### ISSUE TITLE
Please add a license to the repository

### ISSUE THREAD

**Issue by greschd** [MattBystrin/premake-ecc#2]
Hi @MattBystrin

Thanks for making your code available. Unfortunately, without a license, I'm unsure if (and under what conditions) I can use it.

Would you mind adding a license to the repository to clarify?

Thanks!

**Comment by MattBystrin** [comment]
Hi @greschd !

Sure ! Just wait a little bit

**Comment by greschd** [comment]
Awesome, that was quick! Thanks @MattBystrin!
