### ISSUE TITLE
Missing C++ standard specification flags

### ISSUE THREAD

**Issue by VolodymyrKuksa** [MattBystrin/premake-ecc#3]
Hello,

Thanks for the awesome module, I'm using it to set up LSP via clangd for my C/C++ project.

I've noticed that the generated compile_commands.json is missing `-std=C++xx` flag for C++ files. This causes some LSP errors when using features of a standard that is different from the default one (C++14 for Clang).

I think I've managed to find a fix for this by changing [this line](https://github.com/MattBystrin/premake-ecc/blob/2ad563c55fa0021b6e7cdb02c42a2f101cd83802/ecc.lua#L67) to use _toolset.getc**xx**flags()_

Could you please check if this would be a viable solution for the problem?

**Comment by MattBystrin** [comment]
Hello, @VolodymyrKuksa !

Thanks for finding bugs ! I'll fix this in a couple days.

Could you please tell what version of clangd and premake you are using ?

**Comment by VolodymyrKuksa** [comment]
Hi!
Thanks for the quick reply!

Premake:
`premake5 (Premake Build Script Generator) 5.0.0-beta1`
clangd:
`Apple clangd version 14.0.0 (clang-1400.0.29.202)
Features: mac+xpc
Platform: x86_64-apple-darwin22.1.0`
I'm running macOS 13.0.1

I hope this info helps!

**Comment by MattBystrin** [comment]
@VolodymyrKuksa , one more question.

Are you using clang compiler? Because I didn't find any issues with gcc

**Comment by VolodymyrKuksa** [comment]
@MattBystrin , yes I do use clang (the one shipped with XCode).
I don't think the issue is with clang as the problem is that the option never showed up in the `compile_commands.json` file. There may be some difference in how premake handles this on macOS though.

**Comment by VolodymyrKuksa** [comment]
I've investigated the premake codebase a bit more and here's what I found:  

[gcc.getcppflags](https://github.com/premake/premake-core/blob/fb89d40bbb66029f3a76b522dd01bb8b2303d0f4/src/tools/gcc.lua#L28):
```lua
--
-- Returns list of C preprocessor flags for a configuration.
--

	gcc.cppflags = {
		system = {
			haiku = "-MMD",
			wii = { "-MMD", "-MP", "-I$(LIBOGC_INC)", "$(MACHDEP)" },
			_ = { "-MD", "-MP" }
		}
	}

	function gcc.getcppflags(cfg)
		local flags = config.mapFlags(cfg, gcc.cppflags)
		return flags
	end
```
  
[gcc.getcxxflags](https://github.com/premake/premake-core/blob/fb89d40bbb66029f3a76b522dd01bb8b2303d0f4/src/tools/gcc.lua#L246):
```lua
	function gcc.getcxxflags(cfg)
		local shared_flags = config.mapFlags(cfg, gcc.shared)
		local cxxflags = config.mapFlags(cfg, gcc.cxxflags)
		local flags = table.join(shared_flags, cxxflags)
		flags = table.join(flags, gcc.getwarnings(cfg), gcc.getsystemversionflags(cfg))
		return flags
	end
```

So it looks like the `getcppflags()` returns a set of predefined flags based on the system. So to fix the issue we need to call both of the methods, as `getcxxflags` will also provide a range of other flags (see [`gcc.cxxflags`](https://github.com/premake/premake-core/blob/fb89d40bbb66029f3a76b522dd01bb8b2303d0f4/src/tools/gcc.lua#L201)). The clang generator is pretty much the same.
  
@MattBystrin, you mentioned that you didn't have this issue before. Could you please check if you have appropriate `-std=C++xx` flags in your `compile_commands.json` when setting a `cppdialect` for a premake project?

**Comment by MattBystrin** [comment]
@VolodymyrKuksa , that's the point !
I've never used cppdialect option.
Gonna test it out.

Thanks for your work! You can create a merge request to become a contributor )

**Comment by VolodymyrKuksa** [comment]
@MattBystrin, here you go: https://github.com/MattBystrin/premake-ecc/pull/4

**Comment by MattBystrin** [comment]
@VolodymyrKuksa, thanks for your contribution !

The situation was worse than I thought. It was a bad idea (my idea)  to mix flags because  `-g` appears twice. Also I've add defines and undefines flags. 

Could you please check if everything works fine in `flags_fix` branch ?

**Comment by VolodymyrKuksa** [comment]
The module from the flags_fix branch produces invalid json output, I'm missing a coma between some of the declarations:
<img width="968" alt="image" src="https://user-images.githubusercontent.com/32491813/211048078-7078e818-8315-41b2-8df7-099bcfbae503.png">
I believe that this is caused by the fact that these files come from different premake projects.

**Comment by VolodymyrKuksa** [comment]
Looks like you should also check if you're processing the last file **in the last project** here: https://github.com/MattBystrin/premake-ecc/blob/e8a74ef18d5abfda274f74d8a8d14f7b52b4ada9/ecc.lua#L35

**Comment by MattBystrin** [comment]
Yep, also I have to check if I'm parsing last workspace if there exists more than one. Thinking about solution ...

**Comment by MattBystrin** [comment]
As I can see the last comma do not breaks things, but looks ugly. This deserves its own issue.
@VolodymyrKuksa, do you have any problems now ?

**Comment by VolodymyrKuksa** [comment]
Thanks for looking into this, @MattBystrin !
Everything seems to work fine now.
