### ISSUE TITLE
Error on launching

### ISSUE THREAD

**Issue by Hatrickek** [MattBystrin/premake-ecc#6]
Even though I have put the ecc folder in correct search path for premake (since it can find the lua files). I still get `no such action 'ecc'` when I run `premake ecc`. What could be causing this?

Btw I have tried the same way I load ecc with other modules and they just work.

**Comment by MattBystrin** [comment]
Hi @Hatrickek !

Did you rebuild premake embedding ecc module?
Have you read [this](https://premake.github.io/docs/Embedding-Modules/) manual?
Could you please provide links to other modules you mention?

Also could you please provide an example of `premake5.lua` file for me to make tests locally?

**Comment by Hatrickek** [comment]
Paths were mixed up, now it all works sorry for the inconvenience.
