### ISSUE TITLE
Error: no such action 'ecc'

### ISSUE THREAD

**Issue by dylsonowski** [MattBystrin/premake-ecc#7]
Hello, 
I followed all of the guide on embeding module and I'm still getting error why trying to execute `premake5 ecc`. Any suggestions why it cannot work?

**Comment by MattBystrin** [comment]
Hi! Could you please provide more details ? At least I need to know premake version

**Comment by dylsonowski** [comment]
Sure thing sorry. I'm using newest premake5-beta2
It would take to much time to describe structure of my repo so I'll just link it here https://github.com/dylsonowski/AI-Playground/tree/master/scripts

**Comment by MattBystrin** [comment]
@dylsonowski I found that module was not having capability to run without embedding. I fixed this bug and tested locally
To use module in your case you need to fix premake script a little:
```
require "ecc/ecc"
```

**Comment by dylsonowski** [comment]
@MattBystrin I was already trying to do it the way you suggested but it didn't work eather. I commited changes that you suggested to repo.

**Comment by MattBystrin** [comment]
@dylsonowski , I have cloned your repo and updated ecc folder. Everything works fine. Maybe you forget to pull changes from my module?

**Comment by dylsonowski** [comment]
Oh, ok you are wright. Now everything works perfectly. Thank you
